from enum import Enum

# from https://github.com/LemmyNet/lemmy/blob/c216153dfb3cb2d08b72fa466fe522b3c7accde7/migrations/2022-06-21-123144_language-tags/up.sql

class LanguageType(Enum):
    Undetermined = 0
    aa_iso = 1 # Afaraf
    ab_iso = 2 # аҧсуа бызшәа
    ae_iso = 3 # avesta
    af_iso = 4 # Afrikaans
    ak_iso = 5 # Akan
    am_iso = 6 # አማርኛ
    an_iso = 7 # aragonés
    ar_iso = 8 # اَلْعَرَبِيَّةُ
    as_iso = 9 # অসমীয়া
    av_iso = 10 # авар мацӀ
    ay_iso = 11 # aymar aru
    az_iso = 12 # azərbaycan dili
    ba_iso = 13 # башҡорт теле
    be_iso = 14 # беларуская мова
    bg_iso = 15 # български език
    bi_iso = 16 # Bislama
    bm_iso = 17 # bamanankan
    bn_iso = 18 # বাংলা
    bo_iso = 19 # བོད་ཡིག
    br_iso = 20 # brezhoneg
    bs_iso = 21 # bosanski jezik
    ca_iso = 22 # Català
    ce_iso = 23 # нохчийн мотт
    ch_iso = 24 # Chamoru
    co_iso = 25 # corsu
    cr_iso = 26 # ᓀᐦᐃᔭᐍᐏᐣ
    cs_iso = 27 # čeština
    cu_iso = 28 # ѩзыкъ словѣньскъ
    cv_iso = 29 # чӑваш чӗлхи
    cy_iso = 30 # Cymraeg
    da_iso = 31 # dansk
    de_iso = 32 # Deutsch
    dv_iso = 33 # ދިވެހި
    dz_iso = 34 # རྫོང་ཁ
    ee_iso = 35 # Eʋegbe
    el_iso = 36 # Ελληνικά
    en_iso = 37 # English
    eo_iso = 38 # Esperanto
    es_iso = 39 # Español
    et_iso = 40 # eesti
    eu_iso = 41 # euskara
    fa_iso = 42 # فارسی
    ff_iso = 43 # Fulfulde
    fi_iso = 44 # suomi
    fj_iso = 45 # vosa Vakaviti
    fo_iso = 46 # føroyskt
    fr_iso = 47 # Français
    fy_iso = 48 # Frysk
    ga_iso = 49 # Gaeilge
    gd_iso = 50 # Gàidhlig
    gl_iso = 51 # galego
    gn_iso = 52 # Avañe\'ẽ
    gu_iso = 53 # ગુજરાતી
    gv_iso = 54 # Gaelg
    ha_iso = 55 # هَوُسَ
    he_iso = 56 # עברית
    hi_iso = 57 # हिन्दी
    ho_iso = 58 # Hiri Motu
    hr_iso = 59 # Hrvatski
    ht_iso = 60 # Kreyòl ayisyen
    hu_iso = 61 # magyar
    hy_iso = 62 # Հայերեն
    hz_iso = 63 # Otjiherero
    ia_iso = 64 # Interlingua
    id_iso = 65 # Bahasa Indonesia
    ie_iso = 66 # Interlingue
    ig_iso = 67 # Asụsụ Igbo
    ii_iso = 68 # ꆈꌠ꒿ Nuosuhxop
    ik_iso = 69 # Iñupiaq
    io_iso = 70 # Ido
    is_iso = 71 # Íslenska
    it_iso = 72 # Italiano
    iu_iso = 73 # ᐃᓄᒃᑎᑐᑦ
    ja_iso = 74 # 日本語
    jv_iso = 75 # basa Jawa
    ka_iso = 76 # ქართული
    kg_iso = 77 # Kikongo
    ki_iso = 78 # Gĩkũyũ
    kj_iso = 79 # Kuanyama
    kk_iso = 80 # қазақ тілі
    kl_iso = 81 # kalaallisut
    km_iso = 82 # ខេមរភាសា
    kn_iso = 83 # ಕನ್ನಡ
    ko_iso = 84 # 한국어
    kr_iso = 85 # Kanuri
    ks_iso = 86 # कश्मीरी
    ku_iso = 87 # Kurdî
    kv_iso = 88 # коми кыв
    kw_iso = 89 # Kernewek
    ky_iso = 90 # Кыргызча
    la_iso = 91 # latine
    lb_iso = 92 # Lëtzebuergesch
    lg_iso = 93 # Luganda
    li_iso = 94 # Limburgs
    ln_iso = 95 # Lingála
    lo_iso = 96 # ພາສາລາວ
    lt_iso = 97 # lietuvių kalba
    lu_iso = 98 # Kiluba
    lv_iso = 99 # latviešu valoda
    mg_iso = 100 # fiteny malagasy
    mh_iso = 101 # Kajin M̧ajeļ
    mi_iso = 102 # te reo Māori
    mk_iso = 103 # македонски јазик
    ml_iso = 104 # മലയാളം
    mn_iso = 105 # Монгол хэл
    mr_iso = 106 # मराठी
    ms_iso = 107 # Bahasa Melayu
    mt_iso = 108 # Malti
    my_iso = 109 # ဗမာစာ
    na_iso = 110 # Dorerin Naoero
    nb_iso = 111 # Norsk bokmål
    nd_iso = 112 # isiNdebele
    ne_iso = 113 # नेपाली
    ng_iso = 114 # Owambo
    nl_iso = 115 # Nederlands
    nn_iso = 116 # Norsk nynorsk
    no_iso = 117 # Norsk
    nr_iso = 118 # isiNdebele
    nv_iso = 119 # Diné bizaad
    ny_iso = 120 # chiCheŵa
    oc_iso = 121 # occitan
    oj_iso = 122 # ᐊᓂᔑᓈᐯᒧᐎᓐ
    om_iso = 123 # Afaan Oromoo
    or_iso = 124 # ଓଡ଼ିଆ
    os_iso = 125 # ирон æвзаг
    pa_iso = 126 # ਪੰਜਾਬੀ
    pi_iso = 127 # पाऴि
    pl_iso = 128 # Polski
    ps_iso = 129 # پښتو
    pt_iso = 130 # Português
    qu_iso = 131 # Runa Simi
    rm_iso = 132 # rumantsch grischun
    rn_iso = 133 # Ikirundi
    ro_iso = 134 # Română
    ru_iso = 135 # Русский
    rw_iso = 136 # Ikinyarwanda
    sa_iso = 137 # संस्कृतम्
    sc_iso = 138 # sardu
    sd_iso = 139 # सिन्धी
    se_iso = 140 # Davvisámegiella
    sg_iso = 141 # yângâ tî sängö
    si_iso = 142 # සිංහල
    sk_iso = 143 # slovenčina
    sl_iso = 144 # slovenščina
    sm_iso = 145 # gagana fa\'a Samoa
    sn_iso = 146 # chiShona
    so_iso = 147 # Soomaaliga
    sq_iso = 148 # Shqip
    sr_iso = 149 # српски језик
    ss_iso = 150 # SiSwati
    st_iso = 151 # Sesotho
    su_iso = 152 # Basa Sunda
    sv_iso = 153 # Svenska
    sw_iso = 154 # Kiswahili
    ta_iso = 155 # தமிழ்
    te_iso = 156 # తెలుగు
    tg_iso = 157 # тоҷикӣ
    th_iso = 158 # ไทย
    ti_iso = 159 # ትግርኛ
    tk_iso = 160 # Türkmençe
    tl_iso = 161 # Wikang Tagalog
    tn_iso = 162 # Setswana
    to_iso = 163 # faka Tonga
    tr_iso = 164 # Türkçe
    ts_iso = 165 # Xitsonga
    tt_iso = 166 # татар теле
    tw_iso = 167 # Twi
    ty_iso = 168 # Reo Tahiti
    ug_iso = 169 # ئۇيغۇرچە‎
    uk_iso = 170 # Українська
    ur_iso = 171 # اردو
    uz_iso = 172 # Ўзбек
    ve_iso = 173 # Tshivenḓa
    vi_iso = 174 # Tiếng Việt
    vo_iso = 175 # Volapük
    wa_iso = 176 # walon
    wo_iso = 177 # Wollof
    xh_iso = 178 # isiXhosa
    yi_iso = 179 # ייִדיש
    yo_iso = 180 # Yorùbá
    za_iso = 181 # Saɯ cueŋƅ
    zh_iso = 182 # 中文
    zu_iso = 183 # isiZulu
